version: 2.1

orbs:
  android: circleci/android@1.0.3

references:
  android_config: &android_config
    executor:
      name: android/android-machine
      resource-class: large
    environment:
      # Configure the JVM and Gradle to avoid OOM errors
      _JAVA_OPTIONS: "-Xmx4g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"

  #  android_dependencies: &android_dependencies
  #    run:
  #      name: Download Dependencies
  #      command: ./gradlew androidDependencies

jobs:
  debug-build:
    <<: *android_config
    steps:
      - checkout
      #      - *android_dependencies
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Build PropertyManagementModule
          command: ./gradlew clean assembleDebug
#      - save_cache:
#          paths:
#            - ~/.gradle
#          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
  #      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
  #          path: app/build/reports
  #          destination: reports
  #      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
  #          path: app/build/test-results
workflows:
  version: 2
  workflow:
    jobs:
      - debug-build:
          filters:
            tags:
              only: /.*/