version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/android:api-28
    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Build
          command: ./gradlew bundleDebugAar
      - run:
          name: Run Tests
          command: ./gradlew test