version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    steps:
      - checkout
      - run:
          name: Install and download Gradle
          command: wget https://services.gradle.org/distributions/gradle-6.9.1-bin.zip
            unzip -d /opt gradle-6.9.1-bin.zip
            echo $PATH
            export PATH=$PATH:/opt/gradle-6.9.1/bin

      - run:
          name: Build and Test
          command: ./gradlew build

      - run:
          name: Publish to JitPack
          command: |
            curl -L https://github.com/jitpack/jitpack-cli/releases/download/v1.4.1/jitpack-cli-1.4.1.jar -o jitpack-cli.jar
            java -jar jitpack-cli.jar --build --no-notify --release
            echo "Library published to JitPack."

workflows:
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*(-[a-zA-Z0-9]+(\.[a-zA-Z0-9]+)*)?$/
